export type MemberTool = {
  title: string;
  description: string;
  href: string;
  label: string;
  status: 'Ready' | 'Needs WordPress Page' | 'API Pending' | 'Admin Only';
};

export type MemberEndpoint = {
  name: string;
  method: 'GET';
  path: string;
  purpose: string;
  access: 'Public' | 'Authenticated Member' | 'Administrator';
};

export const MEMBERS_WORDPRESS_BASE_URL = process.env.NEXT_PUBLIC_MEMBERS_WORDPRESS_BASE_URL || 'https://onegodian.org';

export const memberTools: MemberTool[] = [
  {
    title: 'Member Dashboard',
    description: 'Open the WordPress member dashboard powered by the OneGodian Members Plugin shortcode.',
    href: `${MEMBERS_WORDPRESS_BASE_URL}/member-dashboard/`,
    label: 'Open Dashboard',
    status: 'Needs WordPress Page'
  },
  {
    title: 'Get Certificate',
    description: 'View, print, and download the member certificate generated by the plugin certificate module.',
    href: `${MEMBERS_WORDPRESS_BASE_URL}/member-certificate/`,
    label: 'Get Certificate',
    status: 'Needs WordPress Page'
  },
  {
    title: 'Member Resources',
    description: 'Access member documents, onboarding resources, education links, and membership support material.',
    href: `${MEMBERS_WORDPRESS_BASE_URL}/member-resources/`,
    label: 'Open Resources',
    status: 'Needs WordPress Page'
  },
  {
    title: 'Membership Pricing',
    description: 'Review membership plans, access levels, and subscription or contribution options.',
    href: `${MEMBERS_WORDPRESS_BASE_URL}/membership-pricing/`,
    label: 'View Pricing',
    status: 'Needs WordPress Page'
  },
  {
    title: 'Account / Orders',
    description: 'Open the WordPress account area for purchases, downloads, orders, and account details.',
    href: `${MEMBERS_WORDPRESS_BASE_URL}/my-account/`,
    label: 'Open Account',
    status: 'Ready'
  },
  {
    title: 'Members Admin',
    description: 'Open the OneGodian Members admin dashboard inside WordPress for plugin status and summary controls.',
    href: `${MEMBERS_WORDPRESS_BASE_URL}/wp-admin/admin.php?page=onegodian-members-dashboard`,
    label: 'Open Admin',
    status: 'Admin Only'
  }
];

export const memberEndpoints: MemberEndpoint[] = [
  {
    name: 'Health Check',
    method: 'GET',
    path: '/wp-json/onegodian-members/v1/health',
    purpose: 'Confirms the OneGodian Members Plugin is installed, active, and reachable from the app.',
    access: 'Public'
  },
  {
    name: 'Current Member',
    method: 'GET',
    path: '/wp-json/onegodian-members/v1/me',
    purpose: 'Returns the authenticated member profile, access status, tools, certificate state, and account data.',
    access: 'Authenticated Member'
  },
  {
    name: 'Admin Summary',
    method: 'GET',
    path: '/wp-json/onegodian-members/v1/admin/summary',
    purpose: 'Returns member totals, premium counts, contributor counts, elder counts, and administrative status data.',
    access: 'Administrator'
  }
];

export const membersProductionChecklist = [
  'Install OneGodian Members Plugin v1.1.0 on the WordPress membership site',
  'Set NEXT_PUBLIC_MEMBERS_WORDPRESS_BASE_URL in the app environment',
  'Create /member-dashboard/ using [onegodian_members_dashboard]',
  'Create /member-certificate/ using [onegodian_member_certificate]',
  'Create /member-resources/ using [onegodian_member_resources]',
  'Create /membership-pricing/ using [onegodian_members_pricing]',
  'Confirm the plugin health endpoint returns a valid JSON response',
  'Connect authenticated member sessions before exposing protected member data in the app',
  'Add QR-V or OBP-1 verification links for certificate numbers when the verifier is ready'
];
