version: "3.9"

services:
  instryx:
    build: .
    ports:
      - "4010:4010"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: .
    command: npm run build && npm run worker
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
