<?php
/**
 * Plugin Name: Algonquian Marketplace
 * Description: Marketplace foundations for wholesale deals, investor access, syndication, buyer subscriptions, and premium listings.
 * Version: 0.1.0
 * Author: Algonquian Real Estate
 * Requires Plugins: algq-core
 */

if (!defined('ABSPATH')) {
    exit;
}

defined('ALGQ_MARKETPLACE_VERSION') || define('ALGQ_MARKETPLACE_VERSION', '0.1.0');
defined('ALGQ_MARKETPLACE_FILE') || define('ALGQ_MARKETPLACE_FILE', __FILE__);
defined('ALGQ_MARKETPLACE_DIR') || define('ALGQ_MARKETPLACE_DIR', plugin_dir_path(__FILE__));
defined('ALGQ_MARKETPLACE_URL') || define('ALGQ_MARKETPLACE_URL', plugin_dir_url(__FILE__));

require_once ALGQ_MARKETPLACE_DIR . 'includes/class-algq-marketplace-sanitizer.php';
require_once ALGQ_MARKETPLACE_DIR . 'includes/class-algq-marketplace-activator.php';
require_once ALGQ_MARKETPLACE_DIR . 'includes/class-algq-marketplace-plugin.php';

function algq_marketplace_core_available(): bool
{
    if (function_exists('algq_core')) {
        return true;
    }

    add_action('admin_notices', static function (): void {
        echo '<div class="notice notice-error"><p>' . esc_html__('Algonquian Marketplace requires the Algonquian Core plugin to be active.', 'algq-marketplace') . '</p></div>';
    });

    return false;
}

/**
 * Return the marketplace module definitions used by the public shortcode and REST snapshot.
 *
 * @return array<int, array{label: string, description: string, status: string}>
 */
function algq_marketplace_modules(): array
{
    return Algq_Marketplace_Plugin::modules();
}

/**
 * Return page definitions generated by the marketplace activation workflow.
 *
 * @return array<int, array{slug: string, title: string, content: string, option_name: string}>
 */
function algq_marketplace_generated_pages(): array
{
    return Algq_Marketplace_Activator::generated_pages();
}

register_activation_hook(__FILE__, ['Algq_Marketplace_Activator', 'activate']);

add_action('plugins_loaded', static function (): void {
    if (!algq_marketplace_core_available()) {
        return;
    }

    algq_marketplace()->register();
});

function algq_marketplace(): Algq_Marketplace_Plugin
{
    static $plugin = null;

    if (!$plugin instanceof Algq_Marketplace_Plugin) {
        $plugin = new Algq_Marketplace_Plugin();
    }

    return $plugin;
}
