import { notFound } from 'next/navigation'; import { PageHero } from '@/components/ODC';
const content:Record<string,{title:string;sections:[string,string][]}>={
'getting-started':{title:'Getting started',sections:[['What is ODC?','ODC is an ERC-20 digital utility token on Ethereum Mainnet. Verify the full official contract before receiving or sending it.'],['Wallets and fees','Use a compatible Ethereum wallet, select Ethereum Mainnet, and protect your seed phrase. Sending ODC requires ETH for network transaction fees.']]},
'token':{title:'Token documentation',sections:[['Identity and compatibility','ODC uses the ERC-20 standard, 18 decimals, and a stated maximum supply of 777,000,000,000 ODC.'],['History and utility','Previously called Onegodian DiFi Coin, ODC retains its ticker and contract. Utility categories have explicit readiness states.']]},
'contract':{title:'Contract documentation',sections:[['Verification','The official address is 0x9eee1e3615efe0374a7588d2760db5ffb2d5ce98 on Ethereum Mainnet.'],['Permissions and audit distinction','Administrative controls remain verification pending. Source verification does not constitute an independent audit.']]},
'wallets':{title:'Wallet and security',sections:[['Safe wallet use','Verify Ethereum Mainnet and the full contract. Never disclose private keys or seed phrases, and regularly review token approvals.'],['Phishing and finality','Reject impersonation sites and unsolicited signing requests. Ethereum transactions are generally irreversible.']]},
'developers':{title:'Developer documentation',sections:[['Public API','Read-only endpoints use a success/error envelope with timestamps and version metadata. Explorer parameters are validated.'],['Operations','Authentication is not required for static public records. Apply rate limits to explorer searches; handle 503 provider-unavailable errors; use additive versioning.']]},
'architecture':{title:'Architecture',sections:[['System design','Next.js serves the responsive public platform and read-only JSON APIs. Ethereum Mainnet is the authoritative token ledger; the platform publishes canonical metadata without signing transactions.'],['Trust boundary','Clients and the WordPress bridge consume public endpoints. No wallet private key, seed phrase, or custody data enters the platform.']]},
'api':{title:'API',sections:[['Response contract','Every endpoint returns version, ISO-8601 timestamp, status, and data. Responses include public cache directives.'],['Endpoints','GET /api/health, /api/manifest, /api/token, /api/contract, /api/supply, /api/status, /api/ecosystem, /api/announcements, and /api/docs.']]},
'deployment':{title:'Deployment',sections:[['Target','The main branch deploys to https://odc.onegodian.com using the standalone Next.js build.'],['Release flow','Install locked dependencies, run typecheck, lint, tests, and build; deploy immutable output; verify health and status; retain the prior release for rollback.']]},
'security':{title:'Security',sections:[['Controls','CSP, HSTS, anti-framing, content-type, permissions-policy, referrer-policy, request IDs, input validation, and rate limiting protect the public surface.'],['Secret rotation','Keep versioned secrets in the deployment secret manager. Add the next version, deploy, validate, revoke the old version, and record the change. Never commit secrets.']]},
'wordpress-bridge':{title:'WordPress Bridge',sections:[['Compatibility','The OneGodian ODC Plugin may read health, manifest, token, contract, supply, and status endpoints.'],['Safety','Treat responses as public, cached metadata. Do not transmit private keys, seed phrases, signing requests, or custody information.']]},
'disclosures':{title:'Disclosures',sections:[['Scope','The platform provides public technical information, not financial, legal, or tax advice. Features not marked Production are unavailable.'],['Risk','Blockchain and digital assets involve smart-contract, network, regulatory, liquidity, and market risks. Independently verify the full contract.']]},
'version-history':{title:'Version History',sections:[['v1.0.0 — 2026-07-25','Initial public platform, dashboard status surface, administration modules, API suite, security controls, SEO assets, and production documentation.']]},
'production-checklist':{title:'Production Checklist',sections:[['Automated validation','Node boots; typecheck, lint, tests, and build pass; APIs return valid envelopes; health returns OK; manifest parses.'],['Release validation','Confirm status accuracy, responsive layouts, accessibility, security headers, documentation, production environment, monitoring, and rollback readiness.']]}}
export function generateStaticParams(){return Object.keys(content).map(slug=>({slug}))} export default function Doc({params}:{params:{slug:string}}){const d=content[params.slug];if(!d)notFound();return <><PageHero eyebrow="Documentation" title={d.title} intro="ODC production platform operating guide."/><article className="prose-section">{d.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}</article></>}
