import Link from 'next/link'; import { ODC_TOKEN, services } from '@/lib/odc'; import { ContractAddress, FeatureStatus } from '@/components/odc';
const utilities=[['Digital products','in-development'],['Platform services','operational'],['Membership-related services','in-development'],['Educational programs','in-development'],['Gaming applications','planned'],['Creator tools','planned'],['Rewards','under-review'],['Marketplace transactions','in-development']] as const;
export default function Home(){return <><section className="cinematic-hero"><div className="hero-grid" aria-hidden="true"/><div className="hero-content"><p className="hero-badge">Ethereum-Based Digital Utility</p><h1>OneGodian Digital Coin</h1><h2>The Digital Utility Token of the OneGodian Ecosystem</h2><p>OneGodian Digital Coin (ODC) is an ERC-20 digital utility token developed by ONEGODIAN, LLC to support approved commerce, memberships, education, gaming, software, digital products, rewards, and platform services across the OneGodian ecosystem.</p><div className="actions"><Link className="button" href="/token">View Token</Link><Link className="button secondary" href="/contract">Verify Contract</Link><Link className="button secondary" href="/explorer">Open Explorer</Link><Link className="button secondary" href="/docs">Read Documentation</Link></div><ContractAddress compact/></div><div className="coin" aria-hidden="true"><span>ODC</span><small>ERC · 20</small></div></section>
<section><div className="section-heading"><p className="eyebrow">Canonical record</p><h2>Token facts</h2></div><div className="fact-grid">{[['Token name',ODC_TOKEN.name],['Symbol',ODC_TOKEN.symbol],['Network',ODC_TOKEN.network],['Standard',ODC_TOKEN.standard],['Maximum supply',ODC_TOKEN.maximumSupplyFormatted],['Decimals',String(ODC_TOKEN.decimals)]].map(([a,b])=><article className="fact" key={a}><span>{a}</span><strong>{b}</strong></article>)}</div></section>
<section className="verification-panel"><p className="eyebrow">Official contract</p><h2>Verify the complete address.</h2><ContractAddress/><div className="actions"><Link className="button secondary" href="/contract">Contract page</Link><a className="button secondary" href={`https://etherscan.io/token/${ODC_TOKEN.contractAddress}`} target="_blank" rel="noreferrer">Ethereum explorer ↗</a></div><p className="warning">⚠ Always verify the full contract address before interacting with ODC. Tokens using the ODC name or symbol with another contract address may be unrelated or fraudulent.</p></section>
<section><div className="section-heading"><p className="eyebrow">Transparent readiness</p><h2>ODC utility</h2></div><div className="status-grid">{utilities.map(([name,status])=><FeatureStatus key={name} name={name} status={status} description="OneGodian ecosystem utility category."/>)}</div></section>
<section><div className="section-heading"><p className="eyebrow">Operational view</p><h2>Platform status</h2></div><div className="status-grid">{services.filter(s=>['Public website','Ethereum RPC','Contract-data service','Explorer service','Documentation','ODC account system','Wallet interface','Payment infrastructure','Marketplace integration','Rewards infrastructure'].includes(s.name)).map(s=><FeatureStatus key={s.name} name={s.name} status={s.state} description={s.description} href={s.href}/>)}</div></section>
<section><div className="section-heading"><p className="eyebrow">Development roadmap</p><h2>Deliberate, verified delivery.</h2></div><ol className="roadmap-strip">{['Public platform','Node infrastructure','WordPress bridge','Controlled utility launch','Ecosystem expansion'].map((x,i)=><li key={x}><span>0{i+1}</span><strong>{x}</strong></li>)}</ol></section>
<section className="security-grid"><div><p className="eyebrow">Security & disclosures</p><h2>Protect every interaction.</h2></div><ul><li>Verify the official contract.</li><li>Never share a private key or seed phrase.</li><li>Blockchain transactions are generally irreversible.</li><li>Etherscan verification is not an independent audit.</li><li>ODC does not guarantee value or liquidity.</li></ul></section>
<section className="cta"><div><p className="eyebrow">Official public platform</p><h2>Explore the ODC Network</h2></div><div className="actions"><Link className="button" href="/explorer">View Explorer</Link><Link className="button secondary" href="/docs">Read the Docs</Link><Link className="button secondary" href="/status">Check Platform Status</Link><Link className="button secondary" href="/disclosures">Review Disclosures</Link></div></section></>}
