import { Hero } from '@/components/Hero';
import { ArchitectureOrbit } from '@/components/ArchitectureOrbit';
import { FrameworkCard } from '@/components/FrameworkCard';
import { PipelineFlow } from '@/components/PipelineFlow';
import { StatusGrid } from '@/components/StatusGrid';
import { EcosystemMap } from '@/components/EcosystemMap';
import { CTASection } from '@/components/CTASection';
import { tools } from '@/data/tools';
import { omosDefinition } from '@/data/omos-pages';

export default function HomePage() { return <main className="space-y-12"><Hero eyebrow="OMOS.OneGodian.com • Operational Intelligence • Protocol Architecture • Alignment Systems" title="The OneGodian Metaphysical Operating System™" subtitle="OMOS™ is the systems-architecture layer of the OneGodian ecosystem: a structured framework for identity recognition, alignment logic, protocol governance, AI interaction standards, and operational intelligence." /><section className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-6"><p className="text-xs font-black uppercase tracking-[0.24em] text-[#F0D98A]">What OMOS Is</p><h2 className="mt-3 text-3xl font-black text-white">Operational intelligence architecture</h2><p className="mt-4 max-w-5xl text-lg leading-8 text-slate-300">{omosDefinition}</p></section><ArchitectureOrbit /><section><h2 className="mb-5 text-3xl font-black text-white">Framework Cards</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{tools.slice(0, 6).map((tool) => <FrameworkCard key={tool.href} {...tool} />)}</div></section><CTASection title="OneGodian Algorithm Preview" href="/algorithm" label="Open Algorithm" /><CTASection title="OneGodian Protocol Preview" href="/protocol" label="Open Protocol" /><section><h2 className="mb-5 text-3xl font-black text-white">OHI Output Pipeline Preview</h2><PipelineFlow /></section><CTASection title="Belief Mapper Preview" href="/belief-mapper" label="Start Belief Mapper" /><CTASection title="System Prompt Preview" href="/system-prompt" label="Open Prompt Center" /><CTASection title="Implementation Map" href="/implementation" label="View Architecture" /><CTASection title="Documentation Hub" href="/docs" label="Read Docs" /><section><h2 className="mb-5 text-3xl font-black text-white">Status Dashboard Preview</h2><StatusGrid /></section><section><h2 className="mb-5 text-3xl font-black text-white">Ecosystem Map</h2><EcosystemMap /></section></main>; }
