import Link from 'next/link';
import { odinSeries, type OdinSeriesItem } from '@/data/odin-series';
import { odinPlanets, type OdinPlanet } from '@/data/odin-planets';

export function OdinHero() { return <section className='rounded-xl border border-violet-400/40 bg-slate-900/70 p-6'><h1 className='text-4xl font-bold text-amber-200'>ODIN Registry™</h1><p className='mt-3 text-slate-200'>The ODIN Registry™ is the OneGodian classification system for technology, law, finance, land, worlds, canon, media, research, and nation-scale assets.</p><p className='mt-3 font-semibold text-blue-300'>No asset, concept, or system exists within the OneGodian ecosystem without an ODIN classification.</p></section>; }
export function OdinSeriesCard({ item }: { item: OdinSeriesItem }) { return <article className='rounded-lg border border-slate-700 bg-slate-900/70 p-4'><p className='text-xs text-violet-300'>{item.code}</p><h3 className='font-semibold text-amber-100'>{item.title}</h3><p className='text-sm text-slate-300'>{item.description}</p></article>; }
export function OdinSeriesGrid({ series = odinSeries, grouped = false }: { series?: OdinSeriesItem[]; grouped?: boolean }) { if (!grouped) return <div className='grid gap-4 md:grid-cols-2'>{series.map((item) => <OdinSeriesCard key={item.code} item={item} />)}</div>; const groups = series.reduce<Record<string, OdinSeriesItem[]>>((acc, item) => { (acc[item.group] ||= []).push(item); return acc; }, {}); return <div className='space-y-6'>{Object.entries(groups).map(([group, items]) => <section key={group}><h2 className='mb-3 text-xl font-semibold text-blue-300'>{group}</h2><div className='grid gap-4 md:grid-cols-2'>{items.map((item) => <OdinSeriesCard key={item.code} item={item} />)}</div></section>)}</div>; }
export function OdinPlanetRegistryTable({ planets = odinPlanets }: { planets?: OdinPlanet[] }) { return <div className='overflow-x-auto rounded-lg border border-slate-700'><table className='min-w-full text-sm'><thead className='bg-slate-900 text-left'><tr>{['PR','ODIN Code','Planet','Title','Group','Function','Actions'].map((h) => <th key={h} className='p-3'>{h}</th>)}</tr></thead><tbody>{planets.map((p)=><tr key={p.pr} className='border-t border-slate-800'><td className='p-3'>{p.pr}</td><td className='p-3'>{p.odin}</td><td className='p-3'>{p.name}</td><td className='p-3'>{p.title}</td><td className='p-3'>{p.group}</td><td className='p-3'>{p.function}</td><td className='p-3'><div className='flex gap-2'><a className='rounded bg-blue-700 px-2 py-1' href={p.canonUrl}>View Canon</a><a className='rounded bg-violet-700 px-2 py-1' href={p.platformUrl}>Enter Planet</a><a className='rounded bg-amber-700 px-2 py-1' href={p.storeUrl}>Visit Store</a></div></td></tr>)}</tbody></table></div>; }
export const OdinCanonNotice = () => <section className='rounded-xl border border-amber-500/40 bg-slate-900/70 p-5'><h2 className='text-2xl font-semibold'>Canon & Authority</h2><ul className='mt-3 list-disc space-y-1 pl-6 text-slate-200'><li>Canon is non-commercial.</li><li>Canon is never gated.</li><li>Canon pages are the source of truth.</li><li>PaaP™ is the planet platform layer.</li><li>Planet Store is commerce only.</li></ul></section>;
export const OdinVerificationPanel = () => <section className='rounded-xl border border-blue-400/40 bg-slate-900/70 p-5'><h2 className='text-2xl font-semibold'>Verification & Provenance</h2><ul className='mt-3 list-disc pl-6'><li>OBP-1™ verification artifacts</li><li>Attestation records</li><li>Provenance trails</li><li>Timestamp authority</li><li>Authenticity seals</li></ul></section>;
export const OdinLayerModel = () => <section className='rounded-xl border border-violet-400/40 bg-slate-900/70 p-5'><h2 className='text-2xl font-semibold'>PaaP™ — Planet-as-a-Platform</h2><ol className='mt-3 list-decimal pl-6'><li>Canon / Registry</li><li>PaaP™ / Platform</li><li>Planet Store / Commerce</li></ol></section>;
export const OdinStatGrid = () => <section className='grid gap-4 sm:grid-cols-3'><div className='rounded-lg border border-slate-700 bg-slate-900/70 p-4'><p className='text-2xl font-bold'>14</p><p>ODIN Series</p></div><div className='rounded-lg border border-slate-700 bg-slate-900/70 p-4'><p className='text-2xl font-bold'>25</p><p>ODIN-PR Worlds</p></div><div className='rounded-lg border border-slate-700 bg-slate-900/70 p-4'><p className='text-2xl font-bold'>3</p><p>PaaP™ Layers</p></div></section>;
export const OdinCtaBand = () => <section className='rounded-xl border border-blue-500/40 bg-gradient-to-r from-slate-900 to-violet-900 p-5'><h2 className='text-xl font-semibold'>Explore the ODIN ecosystem</h2><div className='mt-3 flex flex-wrap gap-3'><Link className='rounded bg-blue-700 px-3 py-2' href='/odin/planetary-registry'>Planetary Registry</Link><Link className='rounded bg-violet-700 px-3 py-2' href='/odin/platforms'>PaaP™ Model</Link></div></section>;
