<?php
if (!defined('ABSPATH')) { exit; }
final class ALGQ_TPC_Shortcodes {
    public static function register() {
        $map = array('algq_trusted_property_contact' => 'landing', 'algq_stewardship_enrollment' => 'enrollment', 'algq_stewardship_client_portal' => 'portal', 'algq_property_visit_form' => 'visit_form', 'algq_stewardship_service_request' => 'request_form', 'algq_stewardship_dashboard' => 'dashboard', 'algq_stewardship_report' => 'reports');
        foreach ($map as $tag => $method) { add_shortcode($tag, array(__CLASS__, $method)); }
    }
    private static function begin() { wp_enqueue_style('algq-stewardship'); wp_enqueue_script('algq-stewardship'); return '<div class="algq-stewardship">'; }
    private static function login_required() { return self::begin() . '<div class="algq-stewardship-notice"><p>' . esc_html__('Please sign in to access secure property information.', 'algq-platform') . '</p>' . wp_login_form(array('echo' => false)) . '</div></div>'; }
    public static function landing() { return self::begin() . '<header class="algq-stewardship-hero"><p class="eyebrow">' . esc_html__('Trusted Property Contact', 'algq-platform') . '</p><h2>' . esc_html__('Confident stewardship when you cannot be there.', 'algq-platform') . '</h2><p>' . esc_html__('Coordinated property visits, maintenance, approvals, secure reporting, and emergency response—always within your written authorization.', 'algq-platform') . '</p><a class="algq-button" href="' . esc_url(home_url('/trusted-property-contact/enroll/')) . '">' . esc_html__('Request enrollment', 'algq-platform') . '</a></header><div class="algq-service-levels"><article><h3>Essential Watch</h3><p>Scheduled observations and condition reports.</p></article><article><h3>Active Steward</h3><p>Visits, vendor coordination, and maintenance oversight.</p></article><article><h3>Transition Support</h3><p>Hands-on coordination for inherited or changing properties.</p></article></div><p class="algq-stewardship-disclaimer">' . esc_html(ALGQ_TPC_Authorization_Service::disclaimer()) . '</p></div>'; }
    public static function enrollment() { return self::begin() . '<h2>' . esc_html__('Stewardship enrollment', 'algq-platform') . '</h2><p>' . esc_html__('Tell us about your property. An ARE coordinator will confirm scope, permissions, spending limits, emergency instructions, and obtain a signed authorization before service begins.', 'algq-platform') . '</p><div class="algq-stewardship-notice">' . esc_html__('For your security, access credentials are collected only through the protected onboarding process—not this public page.', 'algq-platform') . '</div></div>'; }
    public static function portal() {
        if (!is_user_logged_in()) { return self::login_required(); } $properties = ALGQ_TPC_Property_Service::for_current_user();
        $html = self::begin() . '<div class="algq-portal-heading"><div><p class="eyebrow">' . esc_html__('Secure client portal', 'algq-platform') . '</p><h2>' . esc_html__('Your properties', 'algq-platform') . '</h2></div><a class="algq-button" href="' . esc_url(home_url('/property-stewardship/request-service/')) . '">' . esc_html__('Request service', 'algq-platform') . '</a></div>';
        if (!$properties) { $html .= '<p>' . esc_html__('No property records are linked to this account. Contact your ARE coordinator.', 'algq-platform') . '</p>'; }
        foreach ($properties as $property) { $html .= '<article class="algq-property"><h3>' . esc_html($property->address_1) . '</h3><p>' . esc_html(ucwords(str_replace('_', ' ', $property->service_level))) . ' · ' . esc_html(ucwords(str_replace('_', ' ', $property->occupancy_status))) . '</p><dl><dt>' . esc_html__('Service dates', 'algq-platform') . '</dt><dd>' . esc_html($property->service_start . ' — ' . ($property->service_end ?: __('Ongoing', 'algq-platform'))) . '</dd><dt>' . esc_html__('Assigned ARE contact', 'algq-platform') . '</dt><dd>' . esc_html(get_the_author_meta('display_name', $property->assigned_staff_id)) . '</dd></dl></article>'; }
        return $html . '<nav class="algq-portal-nav"><span>Visits</span><span>Reports &amp; photos</span><span>Maintenance</span><span>Approvals &amp; invoices</span><span>Documents</span><span>Secure messages</span></nav></div>';
    }
    public static function request_form() {
        if (!is_user_logged_in()) { return self::login_required(); } $properties = ALGQ_TPC_Property_Service::for_current_user();
        $options = ''; foreach ($properties as $property) { $options .= '<option value="' . esc_attr($property->id) . '">' . esc_html($property->address_1) . '</option>'; }
        return self::begin() . '<h2>' . esc_html__('Submit a service request', 'algq-platform') . '</h2><form class="algq-service-request"><label>Property<select name="property_id" required>' . $options . '</select></label><label>Category<select name="category"><option value="general_maintenance">General maintenance</option><option value="plumbing">Plumbing</option><option value="electrical">Electrical</option><option value="hvac">HVAC</option><option value="landscaping">Landscaping</option><option value="security">Security</option><option value="structural">Structural</option><option value="cleaning">Cleaning</option><option value="storm_damage">Storm damage</option></select></label><label>Priority<select name="priority"><option>normal</option><option>high</option><option>urgent</option></select></label><label>What is needed?<textarea name="description" required></textarea></label><label class="algq-check"><input type="checkbox" name="emergency" value="1"> This requires emergency attention</label><button class="algq-button" type="submit">Submit securely</button><p class="algq-form-status" role="status"></p></form></div>';
    }
    public static function dashboard() { if (!current_user_can('algq_view_stewardship_clients')) { return self::login_required(); } return self::begin() . ALGQ_TPC_Admin::dashboard() . '</div>'; }
    public static function visit_form() { if (!current_user_can('algq_manage_property_visits')) { return self::login_required(); } return self::begin() . '<h2>Property visit</h2><p>Record arrival, checklist results, interior and exterior observations, urgent findings, follow-up actions, and protected date-stamped photographs.</p></div>'; }
    public static function reports() { if (!is_user_logged_in()) { return self::login_required(); } return self::begin() . '<h2>' . esc_html__('Reports and documents', 'algq-platform') . '</h2><p>' . esc_html__('Protected reports and documents available to your account appear here. Every view and download is audited.', 'algq-platform') . '</p></div>'; }
}
